name: AEM CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy from'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -PautoInstallPackage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Upload package to AEM
        env:
          AEM_USERNAME: ${{ secrets.AEM_USERNAME }}
          AEM_PASSWORD: ${{ secrets.AEM_PASSWORD }}
          AEM_HOST: 'http://your-aem-server:4502'
        run: |
          PACKAGE_FILE=$(find . -name "*all.zip" | head -n 1)
          curl -u $AEM_USERNAME:$AEM_PASSWORD -F file=@"$PACKAGE_FILE" -F name=your_package_name -F force=true "$AEM_HOST/crx/packmgr/service.jsp"

      - name: Install package on AEM
        env:
          AEM_USERNAME: ${{ secrets.AEM_USERNAME }}
          AEM_PASSWORD: ${{ secrets.AEM_PASSWORD }}
          AEM_HOST: 'http://your-aem-server:4502'
        run: |
          PACKAGE_NAME=your_package_name
          curl -u $AEM_USERNAME:$AEM_PASSWORD -F cmd=install "$AEM_HOST/crx/packmgr/service/.json/etc/packages/$PACKAGE_NAME"
